version: '3.8'
services:
  web:
    build: 
      context: website
    image: tobinsoft/tobinsoft:v0.0.2
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt/live/tobinsoft.net:/etc/letsencrypt/live/tobinsoft.net
      - /etc/letsencrypt/archive/tobinsoft.net:/etc/letsencrypt/archive/tobinsoft.net
      - ./website/html:/var/www/tobinsoft.net/html
