version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-prod
    image: tobinsoft/tobinsoft:v0.0.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/tobinsoft.net:/ssl
